import { IAnalytic } from "./interfaces/IAnalytic";
import { IEntity } from "./interfaces/IEntity";
import { ITrackingMethod } from "./interfaces/ITrackingMethod";
import { IConfig } from "./interfaces/IConfig";
import { AnalyticModel } from "./models/AnalyticModel";
import { TrackingMethodModel } from "./models/TrackingMethodModel";
import { ANALYTIC_RESULT_TYPE, ALGORITHMS, ANALYTIC_TYPE, TRACK_METHOD, ENTITY_TYPES } from "./constants";
import { AnalyticService } from "./services/AnalyticService";
declare const spinalAnalyticService: AnalyticService;
export { spinalAnalyticService, IAnalytic, ITrackingMethod, IEntity, IConfig, AnalyticModel, TrackingMethodModel, ENTITY_TYPES, ALGORITHMS, ANALYTIC_RESULT_TYPE, ANALYTIC_TYPE, TRACK_METHOD };
export default spinalAnalyticService;
